[package]
name = "aoc"
version = "0.1.5"
authors = ["Thomas Campistron <irevoire@hotmail.fr>"]
edition = "2018"
exclude = ["aoc*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"

[workspace]
members = ["markdown"]
